@isTest
private class OASEzsignbulksenddocumentmappingDeleTest {
    @isTest
    private static void equalsSameInstance() {
        OASEzsignbulksenddocumentmappingDele ezsignbulksenddocumentmappingDeleteObjectV1Response1 = OASEzsignbulksenddocumentmappingDele.getExample();
        OASEzsignbulksenddocumentmappingDele ezsignbulksenddocumentmappingDeleteObjectV1Response2 = ezsignbulksenddocumentmappingDeleteObjectV1Response1;
        OASEzsignbulksenddocumentmappingDele ezsignbulksenddocumentmappingDeleteObjectV1Response3 = new OASEzsignbulksenddocumentmappingDele();
        OASEzsignbulksenddocumentmappingDele ezsignbulksenddocumentmappingDeleteObjectV1Response4 = ezsignbulksenddocumentmappingDeleteObjectV1Response3;

        System.assert(ezsignbulksenddocumentmappingDeleteObjectV1Response1.equals(ezsignbulksenddocumentmappingDeleteObjectV1Response2));
        System.assert(ezsignbulksenddocumentmappingDeleteObjectV1Response2.equals(ezsignbulksenddocumentmappingDeleteObjectV1Response1));
        System.assert(ezsignbulksenddocumentmappingDeleteObjectV1Response1.equals(ezsignbulksenddocumentmappingDeleteObjectV1Response1));
        System.assert(ezsignbulksenddocumentmappingDeleteObjectV1Response3.equals(ezsignbulksenddocumentmappingDeleteObjectV1Response4));
        System.assert(ezsignbulksenddocumentmappingDeleteObjectV1Response4.equals(ezsignbulksenddocumentmappingDeleteObjectV1Response3));
        System.assert(ezsignbulksenddocumentmappingDeleteObjectV1Response3.equals(ezsignbulksenddocumentmappingDeleteObjectV1Response3));
    }

    @isTest
    private static void equalsIdenticalInstance() {
        OASEzsignbulksenddocumentmappingDele ezsignbulksenddocumentmappingDeleteObjectV1Response1 = OASEzsignbulksenddocumentmappingDele.getExample();
        OASEzsignbulksenddocumentmappingDele ezsignbulksenddocumentmappingDeleteObjectV1Response2 = OASEzsignbulksenddocumentmappingDele.getExample();
        OASEzsignbulksenddocumentmappingDele ezsignbulksenddocumentmappingDeleteObjectV1Response3 = new OASEzsignbulksenddocumentmappingDele();
        OASEzsignbulksenddocumentmappingDele ezsignbulksenddocumentmappingDeleteObjectV1Response4 = new OASEzsignbulksenddocumentmappingDele();

        System.assert(ezsignbulksenddocumentmappingDeleteObjectV1Response1.equals(ezsignbulksenddocumentmappingDeleteObjectV1Response2));
        System.assert(ezsignbulksenddocumentmappingDeleteObjectV1Response2.equals(ezsignbulksenddocumentmappingDeleteObjectV1Response1));
        System.assert(ezsignbulksenddocumentmappingDeleteObjectV1Response3.equals(ezsignbulksenddocumentmappingDeleteObjectV1Response4));
        System.assert(ezsignbulksenddocumentmappingDeleteObjectV1Response4.equals(ezsignbulksenddocumentmappingDeleteObjectV1Response3));
    }

    @isTest
    private static void notEqualsDifferentType() {
        OASEzsignbulksenddocumentmappingDele ezsignbulksenddocumentmappingDeleteObjectV1Response1 = OASEzsignbulksenddocumentmappingDele.getExample();
        OASEzsignbulksenddocumentmappingDele ezsignbulksenddocumentmappingDeleteObjectV1Response2 = new OASEzsignbulksenddocumentmappingDele();

        System.assertEquals(false, ezsignbulksenddocumentmappingDeleteObjectV1Response1.equals('foo'));
        System.assertEquals(false, ezsignbulksenddocumentmappingDeleteObjectV1Response2.equals('foo'));
    }

    @isTest
    private static void notEqualsNull() {
        OASEzsignbulksenddocumentmappingDele ezsignbulksenddocumentmappingDeleteObjectV1Response1 = OASEzsignbulksenddocumentmappingDele.getExample();
        OASEzsignbulksenddocumentmappingDele ezsignbulksenddocumentmappingDeleteObjectV1Response2 = new OASEzsignbulksenddocumentmappingDele();
        OASEzsignbulksenddocumentmappingDele ezsignbulksenddocumentmappingDeleteObjectV1Response3;

        System.assertEquals(false, ezsignbulksenddocumentmappingDeleteObjectV1Response1.equals(ezsignbulksenddocumentmappingDeleteObjectV1Response3));
        System.assertEquals(false, ezsignbulksenddocumentmappingDeleteObjectV1Response2.equals(ezsignbulksenddocumentmappingDeleteObjectV1Response3));
    }

    @isTest
    private static void consistentHashCodeValue() {
        OASEzsignbulksenddocumentmappingDele ezsignbulksenddocumentmappingDeleteObjectV1Response1 = OASEzsignbulksenddocumentmappingDele.getExample();
        OASEzsignbulksenddocumentmappingDele ezsignbulksenddocumentmappingDeleteObjectV1Response2 = new OASEzsignbulksenddocumentmappingDele();

        System.assertEquals(ezsignbulksenddocumentmappingDeleteObjectV1Response1.hashCode(), ezsignbulksenddocumentmappingDeleteObjectV1Response1.hashCode());
        System.assertEquals(ezsignbulksenddocumentmappingDeleteObjectV1Response2.hashCode(), ezsignbulksenddocumentmappingDeleteObjectV1Response2.hashCode());
    }

    @isTest
    private static void equalInstancesHaveSameHashCode() {
        OASEzsignbulksenddocumentmappingDele ezsignbulksenddocumentmappingDeleteObjectV1Response1 = OASEzsignbulksenddocumentmappingDele.getExample();
        OASEzsignbulksenddocumentmappingDele ezsignbulksenddocumentmappingDeleteObjectV1Response2 = OASEzsignbulksenddocumentmappingDele.getExample();
        OASEzsignbulksenddocumentmappingDele ezsignbulksenddocumentmappingDeleteObjectV1Response3 = new OASEzsignbulksenddocumentmappingDele();
        OASEzsignbulksenddocumentmappingDele ezsignbulksenddocumentmappingDeleteObjectV1Response4 = new OASEzsignbulksenddocumentmappingDele();

        System.assert(ezsignbulksenddocumentmappingDeleteObjectV1Response1.equals(ezsignbulksenddocumentmappingDeleteObjectV1Response2));
        System.assert(ezsignbulksenddocumentmappingDeleteObjectV1Response3.equals(ezsignbulksenddocumentmappingDeleteObjectV1Response4));
        System.assertEquals(ezsignbulksenddocumentmappingDeleteObjectV1Response1.hashCode(), ezsignbulksenddocumentmappingDeleteObjectV1Response2.hashCode());
        System.assertEquals(ezsignbulksenddocumentmappingDeleteObjectV1Response3.hashCode(), ezsignbulksenddocumentmappingDeleteObjectV1Response4.hashCode());
    }
}
