@isTest
private class OASEzsigntemplateformfieldgroupGetObTest {
    @isTest
    private static void equalsSameInstance() {
        OASEzsigntemplateformfieldgroupGetOb ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload1 = OASEzsigntemplateformfieldgroupGetOb.getExample();
        OASEzsigntemplateformfieldgroupGetOb ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload2 = ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload1;
        OASEzsigntemplateformfieldgroupGetOb ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload3 = new OASEzsigntemplateformfieldgroupGetOb();
        OASEzsigntemplateformfieldgroupGetOb ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload4 = ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload3;

        System.assert(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload1.equals(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload2));
        System.assert(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload2.equals(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload1));
        System.assert(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload1.equals(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload1));
        System.assert(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload3.equals(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload4));
        System.assert(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload4.equals(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload3));
        System.assert(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload3.equals(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload3));
    }

    @isTest
    private static void equalsIdenticalInstance() {
        OASEzsigntemplateformfieldgroupGetOb ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload1 = OASEzsigntemplateformfieldgroupGetOb.getExample();
        OASEzsigntemplateformfieldgroupGetOb ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload2 = OASEzsigntemplateformfieldgroupGetOb.getExample();
        OASEzsigntemplateformfieldgroupGetOb ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload3 = new OASEzsigntemplateformfieldgroupGetOb();
        OASEzsigntemplateformfieldgroupGetOb ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload4 = new OASEzsigntemplateformfieldgroupGetOb();

        System.assert(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload1.equals(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload2));
        System.assert(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload2.equals(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload1));
        System.assert(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload3.equals(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload4));
        System.assert(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload4.equals(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload3));
    }

    @isTest
    private static void notEqualsDifferentType() {
        OASEzsigntemplateformfieldgroupGetOb ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload1 = OASEzsigntemplateformfieldgroupGetOb.getExample();
        OASEzsigntemplateformfieldgroupGetOb ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload2 = new OASEzsigntemplateformfieldgroupGetOb();

        System.assertEquals(false, ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload1.equals('foo'));
        System.assertEquals(false, ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload2.equals('foo'));
    }

    @isTest
    private static void notEqualsNull() {
        OASEzsigntemplateformfieldgroupGetOb ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload1 = OASEzsigntemplateformfieldgroupGetOb.getExample();
        OASEzsigntemplateformfieldgroupGetOb ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload2 = new OASEzsigntemplateformfieldgroupGetOb();
        OASEzsigntemplateformfieldgroupGetOb ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload3;

        System.assertEquals(false, ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload1.equals(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload3));
        System.assertEquals(false, ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload2.equals(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload3));
    }

    @isTest
    private static void consistentHashCodeValue() {
        OASEzsigntemplateformfieldgroupGetOb ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload1 = OASEzsigntemplateformfieldgroupGetOb.getExample();
        OASEzsigntemplateformfieldgroupGetOb ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload2 = new OASEzsigntemplateformfieldgroupGetOb();

        System.assertEquals(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload1.hashCode(), ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload1.hashCode());
        System.assertEquals(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload2.hashCode(), ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload2.hashCode());
    }

    @isTest
    private static void equalInstancesHaveSameHashCode() {
        OASEzsigntemplateformfieldgroupGetOb ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload1 = OASEzsigntemplateformfieldgroupGetOb.getExample();
        OASEzsigntemplateformfieldgroupGetOb ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload2 = OASEzsigntemplateformfieldgroupGetOb.getExample();
        OASEzsigntemplateformfieldgroupGetOb ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload3 = new OASEzsigntemplateformfieldgroupGetOb();
        OASEzsigntemplateformfieldgroupGetOb ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload4 = new OASEzsigntemplateformfieldgroupGetOb();

        System.assert(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload1.equals(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload2));
        System.assert(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload3.equals(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload4));
        System.assertEquals(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload1.hashCode(), ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload2.hashCode());
        System.assertEquals(ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload3.hashCode(), ezsigntemplateformfieldgroupGetObjectV2ResponseMPayload4.hashCode());
    }
}
