@isTest
private class OASEzsignfoldersignerassociationGetITest {
    @isTest
    private static void equalsSameInstance() {
        OASEzsignfoldersignerassociationGetI ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf1 = OASEzsignfoldersignerassociationGetI.getExample();
        OASEzsignfoldersignerassociationGetI ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf2 = ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf1;
        OASEzsignfoldersignerassociationGetI ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf3 = new OASEzsignfoldersignerassociationGetI();
        OASEzsignfoldersignerassociationGetI ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf4 = ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf3;

        System.assert(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf1.equals(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf2));
        System.assert(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf2.equals(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf1));
        System.assert(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf1.equals(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf1));
        System.assert(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf3.equals(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf4));
        System.assert(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf4.equals(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf3));
        System.assert(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf3.equals(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf3));
    }

    @isTest
    private static void equalsIdenticalInstance() {
        OASEzsignfoldersignerassociationGetI ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf1 = OASEzsignfoldersignerassociationGetI.getExample();
        OASEzsignfoldersignerassociationGetI ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf2 = OASEzsignfoldersignerassociationGetI.getExample();
        OASEzsignfoldersignerassociationGetI ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf3 = new OASEzsignfoldersignerassociationGetI();
        OASEzsignfoldersignerassociationGetI ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf4 = new OASEzsignfoldersignerassociationGetI();

        System.assert(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf1.equals(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf2));
        System.assert(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf2.equals(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf1));
        System.assert(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf3.equals(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf4));
        System.assert(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf4.equals(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf3));
    }

    @isTest
    private static void notEqualsDifferentType() {
        OASEzsignfoldersignerassociationGetI ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf1 = OASEzsignfoldersignerassociationGetI.getExample();
        OASEzsignfoldersignerassociationGetI ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf2 = new OASEzsignfoldersignerassociationGetI();

        System.assertEquals(false, ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf1.equals('foo'));
        System.assertEquals(false, ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf2.equals('foo'));
    }

    @isTest
    private static void notEqualsNull() {
        OASEzsignfoldersignerassociationGetI ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf1 = OASEzsignfoldersignerassociationGetI.getExample();
        OASEzsignfoldersignerassociationGetI ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf2 = new OASEzsignfoldersignerassociationGetI();
        OASEzsignfoldersignerassociationGetI ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf3;

        System.assertEquals(false, ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf1.equals(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf3));
        System.assertEquals(false, ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf2.equals(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf3));
    }

    @isTest
    private static void consistentHashCodeValue() {
        OASEzsignfoldersignerassociationGetI ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf1 = OASEzsignfoldersignerassociationGetI.getExample();
        OASEzsignfoldersignerassociationGetI ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf2 = new OASEzsignfoldersignerassociationGetI();

        System.assertEquals(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf1.hashCode(), ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf1.hashCode());
        System.assertEquals(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf2.hashCode(), ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf2.hashCode());
    }

    @isTest
    private static void equalInstancesHaveSameHashCode() {
        OASEzsignfoldersignerassociationGetI ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf1 = OASEzsignfoldersignerassociationGetI.getExample();
        OASEzsignfoldersignerassociationGetI ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf2 = OASEzsignfoldersignerassociationGetI.getExample();
        OASEzsignfoldersignerassociationGetI ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf3 = new OASEzsignfoldersignerassociationGetI();
        OASEzsignfoldersignerassociationGetI ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf4 = new OASEzsignfoldersignerassociationGetI();

        System.assert(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf1.equals(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf2));
        System.assert(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf3.equals(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf4));
        System.assertEquals(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf1.hashCode(), ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf2.hashCode());
        System.assertEquals(ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf3.hashCode(), ezsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf4.hashCode());
    }
}
