@isTest
private class OASEzsignbulksendtransmissionGetObjeTest {
    @isTest
    private static void equalsSameInstance() {
        OASEzsignbulksendtransmissionGetObje ezsignbulksendtransmissionGetObjectV2ResponseMPayload1 = OASEzsignbulksendtransmissionGetObje.getExample();
        OASEzsignbulksendtransmissionGetObje ezsignbulksendtransmissionGetObjectV2ResponseMPayload2 = ezsignbulksendtransmissionGetObjectV2ResponseMPayload1;
        OASEzsignbulksendtransmissionGetObje ezsignbulksendtransmissionGetObjectV2ResponseMPayload3 = new OASEzsignbulksendtransmissionGetObje();
        OASEzsignbulksendtransmissionGetObje ezsignbulksendtransmissionGetObjectV2ResponseMPayload4 = ezsignbulksendtransmissionGetObjectV2ResponseMPayload3;

        System.assert(ezsignbulksendtransmissionGetObjectV2ResponseMPayload1.equals(ezsignbulksendtransmissionGetObjectV2ResponseMPayload2));
        System.assert(ezsignbulksendtransmissionGetObjectV2ResponseMPayload2.equals(ezsignbulksendtransmissionGetObjectV2ResponseMPayload1));
        System.assert(ezsignbulksendtransmissionGetObjectV2ResponseMPayload1.equals(ezsignbulksendtransmissionGetObjectV2ResponseMPayload1));
        System.assert(ezsignbulksendtransmissionGetObjectV2ResponseMPayload3.equals(ezsignbulksendtransmissionGetObjectV2ResponseMPayload4));
        System.assert(ezsignbulksendtransmissionGetObjectV2ResponseMPayload4.equals(ezsignbulksendtransmissionGetObjectV2ResponseMPayload3));
        System.assert(ezsignbulksendtransmissionGetObjectV2ResponseMPayload3.equals(ezsignbulksendtransmissionGetObjectV2ResponseMPayload3));
    }

    @isTest
    private static void equalsIdenticalInstance() {
        OASEzsignbulksendtransmissionGetObje ezsignbulksendtransmissionGetObjectV2ResponseMPayload1 = OASEzsignbulksendtransmissionGetObje.getExample();
        OASEzsignbulksendtransmissionGetObje ezsignbulksendtransmissionGetObjectV2ResponseMPayload2 = OASEzsignbulksendtransmissionGetObje.getExample();
        OASEzsignbulksendtransmissionGetObje ezsignbulksendtransmissionGetObjectV2ResponseMPayload3 = new OASEzsignbulksendtransmissionGetObje();
        OASEzsignbulksendtransmissionGetObje ezsignbulksendtransmissionGetObjectV2ResponseMPayload4 = new OASEzsignbulksendtransmissionGetObje();

        System.assert(ezsignbulksendtransmissionGetObjectV2ResponseMPayload1.equals(ezsignbulksendtransmissionGetObjectV2ResponseMPayload2));
        System.assert(ezsignbulksendtransmissionGetObjectV2ResponseMPayload2.equals(ezsignbulksendtransmissionGetObjectV2ResponseMPayload1));
        System.assert(ezsignbulksendtransmissionGetObjectV2ResponseMPayload3.equals(ezsignbulksendtransmissionGetObjectV2ResponseMPayload4));
        System.assert(ezsignbulksendtransmissionGetObjectV2ResponseMPayload4.equals(ezsignbulksendtransmissionGetObjectV2ResponseMPayload3));
    }

    @isTest
    private static void notEqualsDifferentType() {
        OASEzsignbulksendtransmissionGetObje ezsignbulksendtransmissionGetObjectV2ResponseMPayload1 = OASEzsignbulksendtransmissionGetObje.getExample();
        OASEzsignbulksendtransmissionGetObje ezsignbulksendtransmissionGetObjectV2ResponseMPayload2 = new OASEzsignbulksendtransmissionGetObje();

        System.assertEquals(false, ezsignbulksendtransmissionGetObjectV2ResponseMPayload1.equals('foo'));
        System.assertEquals(false, ezsignbulksendtransmissionGetObjectV2ResponseMPayload2.equals('foo'));
    }

    @isTest
    private static void notEqualsNull() {
        OASEzsignbulksendtransmissionGetObje ezsignbulksendtransmissionGetObjectV2ResponseMPayload1 = OASEzsignbulksendtransmissionGetObje.getExample();
        OASEzsignbulksendtransmissionGetObje ezsignbulksendtransmissionGetObjectV2ResponseMPayload2 = new OASEzsignbulksendtransmissionGetObje();
        OASEzsignbulksendtransmissionGetObje ezsignbulksendtransmissionGetObjectV2ResponseMPayload3;

        System.assertEquals(false, ezsignbulksendtransmissionGetObjectV2ResponseMPayload1.equals(ezsignbulksendtransmissionGetObjectV2ResponseMPayload3));
        System.assertEquals(false, ezsignbulksendtransmissionGetObjectV2ResponseMPayload2.equals(ezsignbulksendtransmissionGetObjectV2ResponseMPayload3));
    }

    @isTest
    private static void consistentHashCodeValue() {
        OASEzsignbulksendtransmissionGetObje ezsignbulksendtransmissionGetObjectV2ResponseMPayload1 = OASEzsignbulksendtransmissionGetObje.getExample();
        OASEzsignbulksendtransmissionGetObje ezsignbulksendtransmissionGetObjectV2ResponseMPayload2 = new OASEzsignbulksendtransmissionGetObje();

        System.assertEquals(ezsignbulksendtransmissionGetObjectV2ResponseMPayload1.hashCode(), ezsignbulksendtransmissionGetObjectV2ResponseMPayload1.hashCode());
        System.assertEquals(ezsignbulksendtransmissionGetObjectV2ResponseMPayload2.hashCode(), ezsignbulksendtransmissionGetObjectV2ResponseMPayload2.hashCode());
    }

    @isTest
    private static void equalInstancesHaveSameHashCode() {
        OASEzsignbulksendtransmissionGetObje ezsignbulksendtransmissionGetObjectV2ResponseMPayload1 = OASEzsignbulksendtransmissionGetObje.getExample();
        OASEzsignbulksendtransmissionGetObje ezsignbulksendtransmissionGetObjectV2ResponseMPayload2 = OASEzsignbulksendtransmissionGetObje.getExample();
        OASEzsignbulksendtransmissionGetObje ezsignbulksendtransmissionGetObjectV2ResponseMPayload3 = new OASEzsignbulksendtransmissionGetObje();
        OASEzsignbulksendtransmissionGetObje ezsignbulksendtransmissionGetObjectV2ResponseMPayload4 = new OASEzsignbulksendtransmissionGetObje();

        System.assert(ezsignbulksendtransmissionGetObjectV2ResponseMPayload1.equals(ezsignbulksendtransmissionGetObjectV2ResponseMPayload2));
        System.assert(ezsignbulksendtransmissionGetObjectV2ResponseMPayload3.equals(ezsignbulksendtransmissionGetObjectV2ResponseMPayload4));
        System.assertEquals(ezsignbulksendtransmissionGetObjectV2ResponseMPayload1.hashCode(), ezsignbulksendtransmissionGetObjectV2ResponseMPayload2.hashCode());
        System.assertEquals(ezsignbulksendtransmissionGetObjectV2ResponseMPayload3.hashCode(), ezsignbulksendtransmissionGetObjectV2ResponseMPayload4.hashCode());
    }
}
